# Generated by Django 5.0.3 on 2024-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Groceries", "Groceries"),
                    ("Transportation", "Transportation"),
                    ("Utilities", "Utilities"),
                    ("Fixed expenses", "Fixed expenses"),
                    ("Savings contributions", "Savings contributions"),
                ],
                max_length=255,
            ),
        ),
    ]
