# Generated by Django 5.0.3 on 2024-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Education", "Education"),
                    ("Groceries", "Groceries"),
                    ("Transportation", "Transportation"),
                    ("Utilities", "Utilities"),
                    ("Fixed expenses", "Fixed expenses"),
                    ("Savings contributions", "Savings contributions"),
                    ("Others", "Others"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Credit card", "Credit card"),
                    ("Debit card", "Debit card"),
                    ("Bank transfer", "Bank transfer"),
                    ("Mobile money", "Mobile money"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
