# Generated by Django 5.0.3 on 2024-03-29 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_budget_category_income"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="amout",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="Category",
            new_name="category",
        ),
    ]
