# Generated by Django 5.0.3 on 2024-03-30 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_amout_budget_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="budget_name",
        ),
        migrations.AddField(
            model_name="budget",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
