# Generated by Django 5.0.3 on 2024-03-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_delete_category_alter_budget_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.FloatField(),
        ),
    ]
