# Generated by Django 5.0.3 on 2024-04-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="avatars/"
            ),
        ),
    ]
